# Read in Alto data

In [5]:
# imports
from importlib import reload
import os
import glob

import numpy as np

from scipy.io import loadmat

import gsw

from matplotlib import pyplot as plt

from profiler import floatdata

import pymatreader

# Load me

In [6]:
dfile = '/home/xavier/Projects/Oceanography/data/ARCTERX/Floats/Alto/tn441_alto_gridded.mat'
d = pymatreader.read_mat(dfile)

In [7]:
d['A'].keys()

dict_keys(['flnum', 'fltype', 'deployment', 'profnum', 'j_badprofiles', 'dn_beg', 'lat_beg', 'lon_beg', 'dn_end', 'lat_end', 'lon_end', 'pgrid', 'temp', 'sal', 'pden'])

## Floats

In [11]:
d['A']['flnum'][0:3]

[11363, 11369, 11373]

In [18]:
# Number of floats
nfloats = len(d['A']['flnum'])
nfloats

23

## Depths

In [21]:
d['A']['pgrid'][0]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

## Temperature

In [9]:
d['A']['temp'][0].shape

(201, 371)

## Profiles

In [23]:
nprof = len(d['A']['profnum'][0])
nprof

371

In [24]:
d['A']['profnum'][0][0:20]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 12., nan,
       nan, nan, nan, nan, nan, nan, nan])

# Times

In [27]:
d['A']['dn_beg'][0].shape

(371,)

## Notes on the data



In [28]:
d['A']['j_badprofiles'][0]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  72,  74,  78, 365, 366, 367,
       368, 369, 370, 371], dtype=uint16)