# Explore Seaglider

## Complements of Luc Rainville

In [1]:
# imports
from importlib import reload
import os
import glob

import numpy as np

from scipy.io import loadmat
import xarray

from matplotlib import pyplot as plt

from profiler import floatdata
#from cugn import gliderpairs
from profiler import utils as cugn_utils
#from profiler import binning

# Load

In [11]:
datafile = '/home/xavier/Projects/Oceanography/data/ARCTERX/2025_IOP/gliders/Seagliders/sg171_ARCTERX_Jan25_level2.nc'
seaglider = xarray.open_dataset(datafile)
seaglider
#vmp.keys()

<xarray.Dataset> Size: 43MB
Dimensions:              (half_profile_data_point: 700, z_data_point: 1001,
                          profile: 350, instrument: 1)
Coordinates:
    time                 (half_profile_data_point, z_data_point) datetime64[ns] 6MB ...
    lat                  (half_profile_data_point, z_data_point) float32 3MB ...
    lon                  (half_profile_data_point, z_data_point) float32 3MB ...
    z                    (z_data_point) float32 4kB ...
    dive                 (half_profile_data_point) int16 1kB ...
Dimensions without coordinates: half_profile_data_point, z_data_point, profile,
                                instrument
Data variables: (12/28)
    S                    (half_profile_data_point, z_data_point) float32 3MB ...
    T                    (half_profile_data_point, z_data_point) float32 3MB ...
    speed                (half_profile_data_point, z_data_point) float32 3MB ...
    ocr504i_chan1        (half_profile_data_point, z_data_point) float32 3MB ...
    ocr504i_chan2        (half_profile_data_point, z_data_point) float32 3MB ...
    ocr504i_chan3        (half_profile_data_point, z_data_point) float32 3MB ...
    ...                   ...
    time_profile         (half_profile_data_point) datetime64[ns] 6kB ...
    lat_profile          (half_profile_data_point) float32 3kB ...
    lon_profile          (half_profile_data_point) float32 3kB ...
    inst_wlbb2fl         (instrument) float64 8B ...
    inst_aa4831          (instrument) float64 8B ...
    inst_ctd             (instrument) float64 8B ...
Attributes: (12/55)
    platform_id:                     SG171
    source:                          seaglider data
    summary:                         SG171 ARCTERX 2025
    project:                         The First- and Second Island Arc Turbule...
    glider:                          171
    mission:                         40
    ...                              ...
    time_coverage_duration:          P20188DT21H32M26S
    geospatial_vertical_min:         0.00
    geospatial_vertical_max:         1000.00
    date_created:                    2025-04-11T17:20:01Z
    date_modified:                   2025-04-11T17:20:01Z
    uuid:                            33712a5c-16f9-11f0-ac2c-92db61350204

In [12]:
seaglider['z'].values

array([   0.,    1.,    2., ...,  998.,  999., 1000.], dtype=float32)

In [13]:
seaglider.dive.values[0:5]

array([1, 1, 2, 2, 3], dtype=int16)

In [5]:
seaglider['profile'].values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [8]:
seaglider.time_profile.values[0:10]

array(['2025-02-03T02:48:32.000000000', '2025-02-03T03:01:20.000000000',
       '2025-02-03T03:29:04.000000000', '2025-02-03T03:41:52.000000000',
       '2025-02-03T04:16:00.000000000', '2025-02-03T04:37:20.000000000',
       '2025-02-03T05:07:12.000000000', '2025-02-03T05:24:16.000000000',
       '2025-02-03T05:47:44.000000000', '2025-02-03T06:06:56.000000000'],
      dtype='datetime64[ns]')

In [13]:
seaglider.time

<xarray.DataArray 'time' (half_profile_data_point: 700, z_data_point: 1001)> Size: 6MB
[700700 values with dtype=datetime64[ns]]
Coordinates:
    time     (half_profile_data_point, z_data_point) datetime64[ns] 6MB ...
    lat      (half_profile_data_point, z_data_point) float32 3MB ...
    lon      (half_profile_data_point, z_data_point) float32 3MB ...
    z        (z_data_point) float32 4kB 0.0 1.0 2.0 3.0 ... 998.0 999.0 1e+03
    dive     (half_profile_data_point) int16 1kB ...
Dimensions without coordinates: half_profile_data_point, z_data_point
Attributes:
    description:            time for every sample point
    axis:                   T
    coverage_content_type:  physicalMeasurement
    standard_name:          time
    long_name:              CTD time

# Properties

## T

In [12]:
seaglider.T

<xarray.DataArray 'T' (half_profile_data_point: 700, z_data_point: 1001)> Size: 3MB
array([[   nan, 24.729, 24.682, ...,    nan,    nan,    nan],
       [   nan, 24.633, 24.658, ...,    nan,    nan,    nan],
       [   nan, 24.718, 24.718, ...,    nan,    nan,    nan],
       ...,
       [   nan, 27.499, 27.494, ...,    nan,    nan,    nan],
       [   nan, 27.463, 27.462, ...,    nan,    nan,    nan],
       [   nan,    nan,    nan, ...,    nan,    nan,    nan]], dtype=float32)
Coordinates:
    time     (half_profile_data_point, z_data_point) datetime64[ns] 6MB ...
    lat      (half_profile_data_point, z_data_point) float32 3MB ...
    lon      (half_profile_data_point, z_data_point) float32 3MB ...
    z        (z_data_point) float32 4kB 0.0 1.0 2.0 3.0 ... 998.0 999.0 1e+03
    dive     (half_profile_data_point) int16 1kB ...
Dimensions without coordinates: half_profile_data_point, z_data_point
Attributes:
    description:            corrected in-situ temperature
    instrument:             inst_ctd
    units:                  degrees_C
    coverage_content_type:  physicalMeasurement
    standard_name:          sea_water_temperature
    long_name:              CTD temperature
    valid_min:              -2.6
    valid_max:              40.0

In [10]:
seaglider.T.values[0:10]

array([[   nan, 24.729, 24.682, ...,    nan,    nan,    nan],
       [   nan, 24.633, 24.658, ...,    nan,    nan,    nan],
       [   nan, 24.718, 24.718, ...,    nan,    nan,    nan],
       ...,
       [24.761, 24.767, 24.766, ...,    nan,    nan,    nan],
       [   nan, 24.761, 24.765, ...,    nan,    nan,    nan],
       [24.717, 24.729, 24.734, ...,    nan,    nan,    nan]],
      dtype=float32)

In [11]:
seaglider.T.shape

(700, 1001)

----

# Dives

In [27]:
dives = np.unique(seaglider.dive.values)

In [28]:
dive = 2
d_bin = seaglider.where(seaglider.dive == dive, drop=True)

In [29]:
d_bin

<xarray.Dataset> Size: 155kB
Dimensions:              (half_profile_data_point: 2, z_data_point: 1001,
                          profile: 350, instrument: 1)
Coordinates:
    time                 (half_profile_data_point, z_data_point) datetime64[ns] 16kB ...
    lat                  (half_profile_data_point, z_data_point) float32 8kB ...
    lon                  (half_profile_data_point, z_data_point) float32 8kB ...
    z                    (z_data_point) float32 4kB 0.0 1.0 2.0 ... 999.0 1e+03
    dive                 (half_profile_data_point) int16 4B 2 2
Dimensions without coordinates: half_profile_data_point, z_data_point, profile,
                                instrument
Data variables: (12/28)
    S                    (half_profile_data_point, z_data_point) float32 8kB ...
    T                    (half_profile_data_point, z_data_point) float32 8kB ...
    speed                (half_profile_data_point, z_data_point) float32 8kB ...
    ocr504i_chan1        (half_profile_data_point, z_data_point) float32 8kB ...
    ocr504i_chan2        (half_profile_data_point, z_data_point) float32 8kB ...
    ocr504i_chan3        (half_profile_data_point, z_data_point) float32 8kB ...
    ...                   ...
    time_profile         (half_profile_data_point) datetime64[ns] 16B 2025-02...
    lat_profile          (half_profile_data_point) float32 8B 20.43 20.42
    lon_profile          (half_profile_data_point) float32 8B 130.0 130.0
    inst_wlbb2fl         (instrument, half_profile_data_point) float64 16B -9...
    inst_aa4831          (instrument, half_profile_data_point) float64 16B -9...
    inst_ctd             (instrument, half_profile_data_point) float64 16B -9...
Attributes: (12/55)
    platform_id:                     SG171
    source:                          seaglider data
    summary:                         SG171 ARCTERX 2025
    project:                         The First- and Second Island Arc Turbule...
    glider:                          171
    mission:                         40
    ...                              ...
    time_coverage_duration:          P20188DT21H32M26S
    geospatial_vertical_min:         0.00
    geospatial_vertical_max:         1000.00
    date_created:                    2025-04-11T17:20:01Z
    date_modified:                   2025-04-11T17:20:01Z
    uuid:                            33712a5c-16f9-11f0-ac2c-92db61350204

In [34]:
tmp = d_bin.mean('half_profile_data_point')
tmp

<xarray.Dataset> Size: 60kB
Dimensions:              (z_data_point: 1001, profile: 350, instrument: 1)
Coordinates:
    z                    (z_data_point) float32 4kB 0.0 1.0 2.0 ... 999.0 1e+03
Dimensions without coordinates: z_data_point, profile, instrument
Data variables: (12/25)
    S                    (z_data_point) float32 4kB nan 34.72 34.72 ... nan nan
    T                    (z_data_point) float32 4kB nan 24.72 24.71 ... nan nan
    speed                (z_data_point) float32 4kB nan 30.67 29.46 ... nan nan
    ocr504i_chan1        (z_data_point) float32 4kB nan 68.19 52.84 ... nan nan
    ocr504i_chan2        (z_data_point) float32 4kB nan 80.71 58.29 ... nan nan
    ocr504i_chan3        (z_data_point) float32 4kB nan 75.12 47.3 ... nan nan
    ...                   ...
    lon_gps              float32 4B 130.0
    lat_profile          float32 4B 20.43
    lon_profile          float32 4B 130.0
    inst_wlbb2fl         (instrument) float64 8B -9.999e+03
    inst_aa4831          (instrument) float64 8B -9.999e+03
    inst_ctd             (instrument) float64 8B -9.999e+03

In [35]:
seaglider.coords

Coordinates:
    time     (half_profile_data_point, z_data_point) datetime64[ns] 6MB ...
    lat      (half_profile_data_point, z_data_point) float32 3MB ...
    lon      (half_profile_data_point, z_data_point) float32 3MB ...
    z        (z_data_point) float32 4kB 0.0 1.0 2.0 3.0 ... 998.0 999.0 1e+03
    dive     (half_profile_data_point) int16 1kB 1 1 2 2 3 ... 349 349 350 350

In [36]:
new_coords = dict(profile=np.arange(350), z_data_point=np.arange(1001))

In [38]:
ds = xarray.Dataset(coords=new_coords)
ds

<xarray.Dataset> Size: 11kB
Dimensions:       (profile: 350, z_data_point: 1001)
Coordinates:
  * profile       (profile) int64 3kB 0 1 2 3 4 5 6 ... 344 345 346 347 348 349
  * z_data_point  (z_data_point) int64 8kB 0 1 2 3 4 5 ... 996 997 998 999 1000
Data variables:
    *empty*

In [24]:
d_bin.time

<xarray.DataArray 'time' (half_profile_data_point: 2, z_data_point: 1001)> Size: 16kB
array([[                          'NaT', '2025-02-03T03:23:02.000000000',
        '2025-02-03T03:23:57.000000000', ...,                           'NaT',
                                  'NaT',                           'NaT'],
       [                          'NaT', '2025-02-03T03:43:25.000000000',
        '2025-02-03T03:43:05.000000000', ...,                           'NaT',
                                  'NaT',                           'NaT']],
      dtype='datetime64[ns]')
Coordinates:
    time     (half_profile_data_point, z_data_point) datetime64[ns] 16kB NaT ...
    lat      (half_profile_data_point, z_data_point) float32 8kB ...
    lon      (half_profile_data_point, z_data_point) float32 8kB ...
    z        (z_data_point) float32 4kB 0.0 1.0 2.0 3.0 ... 998.0 999.0 1e+03
    dive     (half_profile_data_point) int16 4B 2 2
Dimensions without coordinates: half_profile_data_point, z_data_point
Attributes:
    description:            time for every sample point
    axis:                   T
    coverage_content_type:  physicalMeasurement
    standard_name:          time
    long_name:              CTD time

In [19]:
d2.tim

<xarray.Dataset> Size: 60kB
Dimensions:              (z_data_point: 1001, profile: 350, instrument: 1)
Coordinates:
    z                    (z_data_point) float32 4kB 0.0 1.0 2.0 ... 999.0 1e+03
Dimensions without coordinates: z_data_point, profile, instrument
Data variables: (12/25)
    S                    (z_data_point) float32 4kB nan 34.72 34.72 ... nan nan
    T                    (z_data_point) float32 4kB nan 24.72 24.71 ... nan nan
    speed                (z_data_point) float32 4kB nan 30.67 29.46 ... nan nan
    ocr504i_chan1        (z_data_point) float32 4kB nan 68.19 52.84 ... nan nan
    ocr504i_chan2        (z_data_point) float32 4kB nan 80.71 58.29 ... nan nan
    ocr504i_chan3        (z_data_point) float32 4kB nan 75.12 47.3 ... nan nan
    ...                   ...
    lon_gps              float32 4B 130.0
    lat_profile          float32 4B 20.43
    lon_profile          float32 4B 130.0
    inst_wlbb2fl         (instrument) float64 8B -9.999e+03
    inst_aa4831          (instrument) float64 8B -9.999e+03
    inst_ctd             (instrument) float64 8B -9.999e+03

In [42]:
seaglider.z_data_point.values

array([   0,    1,    2, ...,  998,  999, 1000])

In [43]:
seaglider.speed

<xarray.DataArray 'speed' (half_profile_data_point: 700, z_data_point: 1001)> Size: 3MB
[700700 values with dtype=float32]
Coordinates:
    time     (half_profile_data_point, z_data_point) datetime64[ns] 6MB ...
    lat      (half_profile_data_point, z_data_point) float32 3MB ...
    lon      (half_profile_data_point, z_data_point) float32 3MB ...
    z        (z_data_point) float32 4kB 0.0 1.0 2.0 3.0 ... 998.0 999.0 1e+03
    dive     (half_profile_data_point) int16 1kB 1 1 2 2 3 ... 349 349 350 350
Dimensions without coordinates: half_profile_data_point, z_data_point
Attributes:
    description:            forward speed of the glider through the water fro...
    units:                  m s-1
    coverage_content_type:  modelResult