# Explore Slocumb

## Complements of Jesse Cusack

In [2]:
# imports
from importlib import reload
import os
import glob

import numpy as np

from scipy.io import loadmat
import xarray

from matplotlib import pyplot as plt

from profiler import floatdata
#from cugn import gliderpairs
from profiler import utils as cugn_utils
#from profiler import binning

# Load

In [3]:
datafile = '/home/xavier/Projects/Oceanography/data/ARCTERX/gliders/slocumb/osu685.l3.nc'
slocumb = xarray.open_dataset(datafile)
slocumb
#vmp.keys()

<xarray.Dataset> Size: 4MB
Dimensions:       (z: 126, profile_id: 310)
Coordinates:
    depth         (z) float64 1kB ...
  * z             (z) float64 1kB -3.0 -9.0 -15.0 -21.0 ... -741.0 -747.0 -753.0
    profile_time  (profile_id) datetime64[ns] 2kB ...
    profile_lat   (profile_id) float64 2kB ...
    profile_lon   (profile_id) float64 2kB ...
  * profile_id    (profile_id) int64 2kB 1 2 3 4 5 6 ... 305 306 307 308 309 310
Data variables: (12/15)
    conductivity  (z, profile_id) float32 156kB ...
    pressure      (z, profile_id) float32 156kB ...
    temperature   (z, profile_id) float32 156kB ...
    heading       (z, profile_id) float64 312kB ...
    lat           (z, profile_id) float64 312kB ...
    roll          (z, profile_id) float64 312kB ...
    ...            ...
    SA            (z, profile_id) float64 312kB ...
    density       (z, profile_id) float64 312kB ...
    rho0          (z, profile_id) float64 312kB ...
    CT            (z, profile_id) float64 312kB ...
    N2            (z, profile_id) float64 312kB ...
    state         (profile_id) int8 310B ...

In [5]:
slocumb['z']

<xarray.DataArray 'z' (z: 126)> Size: 1kB
array([  -3.,   -9.,  -15.,  -21.,  -27.,  -33.,  -39.,  -45.,  -51.,  -57.,
        -63.,  -69.,  -75.,  -81.,  -87.,  -93.,  -99., -105., -111., -117.,
       -123., -129., -135., -141., -147., -153., -159., -165., -171., -177.,
       -183., -189., -195., -201., -207., -213., -219., -225., -231., -237.,
       -243., -249., -255., -261., -267., -273., -279., -285., -291., -297.,
       -303., -309., -315., -321., -327., -333., -339., -345., -351., -357.,
       -363., -369., -375., -381., -387., -393., -399., -405., -411., -417.,
       -423., -429., -435., -441., -447., -453., -459., -465., -471., -477.,
       -483., -489., -495., -501., -507., -513., -519., -525., -531., -537.,
       -543., -549., -555., -561., -567., -573., -579., -585., -591., -597.,
       -603., -609., -615., -621., -627., -633., -639., -645., -651., -657.,
       -663., -669., -675., -681., -687., -693., -699., -705., -711., -717.,
       -723., -729., -735., -741., -747., -753.])
Coordinates:
    depth    (z) float64 1kB ...
  * z        (z) float64 1kB -3.0 -9.0 -15.0 -21.0 ... -741.0 -747.0 -753.0
Attributes:
    long_name:            Height
    standard_name:        height
    units:                m
    valid_min:            0.0
    valid_max:            -2000.0
    positive:             up
    reference_datum:      sea-surface
    instrument:           instrument_ctd
    observation_type:     calculated
    ancillary_variables:  z_qc

In [7]:
slocumb['profile_id'].values

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [9]:
slocumb.depth.values

array([  3.,   9.,  15.,  21.,  27.,  33.,  39.,  45.,  51.,  57.,  63.,
        69.,  75.,  81.,  87.,  93.,  99., 105., 111., 117., 123., 129.,
       135., 141., 147., 153., 159., 165., 171., 177., 183., 189., 195.,
       201., 207., 213., 219., 225., 231., 237., 243., 249., 255., 261.,
       267., 273., 279., 285., 291., 297., 303., 309., 315., 321., 327.,
       333., 339., 345., 351., 357., 363., 369., 375., 381., 387., 393.,
       399., 405., 411., 417., 423., 429., 435., 441., 447., 453., 459.,
       465., 471., 477., 483., 489., 495., 501., 507., 513., 519., 525.,
       531., 537., 543., 549., 555., 561., 567., 573., 579., 585., 591.,
       597., 603., 609., 615., 621., 627., 633., 639., 645., 651., 657.,
       663., 669., 675., 681., 687., 693., 699., 705., 711., 717., 723.,
       729., 735., 741., 747., 753.])

In [11]:
slocumb.profile_time.values

array(['2025-02-04T01:16:47.000000000', '2025-02-04T01:24:54.137000192',
       '2025-02-04T01:44:57.062000128', '2025-02-04T01:53:04.229000192',
       '2025-02-04T02:29:59.061000192', '2025-02-04T02:38:06.285000192',
       '2025-02-04T09:21:23.000000000', '2025-02-04T10:08:36.665999872',
       '2025-02-04T15:02:47.032999936', '2025-02-04T15:57:43.309999872',
       '2025-02-04T17:08:10.045000192', '2025-02-04T18:06:56.506000128',
       '2025-02-04T19:19:40.936999936', '2025-02-04T20:20:12.272000000',
       '2025-02-04T21:35:16.089999872', '2025-02-04T22:38:35.417999872',
       '2025-02-04T23:56:13.203000064', '2025-02-05T00:59:54.714999808',
       '2025-02-05T02:49:18.000000000', '2025-02-05T03:55:27.009999872',
       '2025-02-05T05:11:15.084999936', '2025-02-05T06:14:35.170000128',
       '2025-02-05T07:38:14.731000064', '2025-02-05T08:24:03.904000000',
       '2025-02-05T09:19:20.121999872', '2025-02-05T10:04:28.507000064',
       '2025-02-05T11:03:14.044000000', '2025-02-05